networks:
  soas-network:
    driver: bridge

services:
  naming-server:
    build: ./NamingServer
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - soas-network
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  users-service:
    build: ./UsersService
    mem_limit: 700m
    ports:
      - "8770:8770"
    networks:
      - soas-network
    restart: on-failure
    depends_on:
      - naming-server
      - bank-account
      - crypto-wallet
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:usersdb

  currency-exchange:
    build: ./CurrencyExchange
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - soas-network
    restart: on-failure
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/

  currency-conversion:
    build: ./CurrencyConversion
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - soas-network
    restart: on-failure
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/

  bank-account:
    build: ./BankAccount
    mem_limit: 700m
    ports:
      - "8200:8200"
    networks:
      - soas-network
    restart: on-failure
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:bankdb

  crypto-wallet:
    build: ./CryptoWallet
    mem_limit: 700m
    ports:
      - "8300:8300"
    networks:
      - soas-network
    restart: on-failure
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:cryptodb

  crypto-exchange:
    build: ./CryptoExchange
    mem_limit: 700m
    ports:
      - "8400:8400"
    networks:
      - soas-network
    restart: on-failure
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/

  trade-service:
    build: ./TradeService
    mem_limit: 700m
    ports:
      - "8600:8600"
    networks:
      - soas-network
    restart: on-failure
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/

  api-gateway:
    build: ./ApiGateway
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - soas-network
    restart: on-failure
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      - USERS_SERVICE_URL=http://users-service:8770