spring.application.name=trade-service
server.port=8600

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.circuitbreaker.instances.tradeService.sliding-window-size=10
resilience4j.circuitbreaker.instances.tradeService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.tradeService.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.tradeService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.tradeService.permitted-number-of-calls-in-half-open-state=3
resilience4j.timelimiter.configs.default.timeout-duration=30s
spring.aop.proxy-target-class=true